### ISSUE TITLE
Cannot get ClassMatchedHandler to work

### ISSUE THREAD

**Issue by mboogerd** [kompics/kompics#30]
I am in the process of implementing the tutorial code on the Kompics website (in Scala), which was very smooth/clear thus far! However, I ran into difficulties when trying to change the Handler implementation for Ping/Pong to a `ClassMatchedHandler`. My implementation for `TMessage` looks as follows:

```scala
case class TMessage(override val getSource: TAddress,
                    override val getDestination: TAddress,
                    override val getProtocol: Transport,
                    payload: KompicsEvent) extends Msg[TAddress, THeader] with PatternExtractor[Class[_], KompicsEvent] {
  override val getHeader: THeader = THeader(getSource, getDestination, getProtocol)
  override val extractValue: KompicsEvent = payload
  override val extractPattern: Class[_] = payload.getClass
}
```

I pass in a _ type parameter to the `Class` type constructor, the first type argument for PatternExtractor. Although this compiles, the Ponger fails at runtime when receiving a Ping message (`TMessage(TAddress(/127.0.0.1,23456),TAddress(/127.0.0.1,12345),TCP,Ping()))`)

```
java.lang.AbstractMethodError: se.sics.kompics.MatchedHandler.handle(Ljava/lang/Object;Lse/sics/kompics/KompicsEvent;)V
	at se.sics.kompics.JavaComponent.executeEvent(JavaComponent.java:402)
	at se.sics.kompics.JavaComponent.execute(JavaComponent.java:343)
...
```

If we look at the call-site's method signature, we see that no type parameters are given for `MatchedHandler`, which makes it default to `Object` and `KompicsEvent`.

```java
private boolean executeEvent(PatternExtractor event, MatchedHandler handler)
```

However, when the implementation for that method looks for a method `handle(_: Object, _: KompicsEvent)`, it cannot find any such method because mine is implemented in terms of `Ping` and `TMessage`, in line with the tutorial.

```scala
val pingHandler = new ClassMatchedHandler[Ping, TMessage]() {
    override def handle(v: Ping, e: TMessage): Unit = {
      counter += 1
      log.info(s"Got Ping #$counter!")
      trigger(TMessage(init.self, e.getSource, Transport.TCP, Pong()), net)
    }
  }
```

I have tried various other setups; for example, replacing `_` type parameter with `KompicsEvent` in `TMessage`. However, this (and all other attempts) fails to compile `subscribe(pongHandler, net)` in `Ponger` due to overloading:

```
Error:(55, 3) overloaded method value subscribe with alternatives:
  (x$1: se.sics.kompics.MatchedHandler[?0(in class MatchedHandler),?1,?2] forSome { type ?0(in class MatchedHandler); type ?1; type ?2 <: se.sics.kompics.KompicsEvent with se.sics.kompics.PatternExtractor[?0(in class MatchedHandler), _ >: ?1] },x$2: se.sics.kompics.Port[_ <: se.sics.kompics.PortType])Unit <and>
  [E <: se.sics.kompics.KompicsEvent, P <: se.sics.kompics.PortType](x$1: se.sics.kompics.Handler[E], x$2: se.sics.kompics.Port[P])Unit
 cannot be applied to (se.sics.kompics.ClassMatchedHandler[com.github.mboogerd.labkompics.pingpong.networking.cleanup.Pong,com.github.mboogerd.labkompics.pingpong.networking.cleanup.model.TMessage[com.github.mboogerd.labkompics.pingpong.networking.cleanup.Pong]], se.sics.kompics.Positive[se.sics.kompics.network.Network])
  subscribe(pongHandler, net)
```

Apologies if I made an error in following the tutorial, but otherwise, it looks like an issue that should play just as much for Java code as it does for Scala code. If you would like to have a closer look at my exact implementation, it is available here:
https://github.com/mboogerd/lab-kompics/tree/classmatchers/src/main/scala/com/github/mboogerd/labkompics/pingpong/networking/cleanup

**Comment by Bathtor** [comment]
Sorry for the slow response, I was on vacation.

Before I spend time (I got a conference deadline coming up, so time is short) looking into this in more detail, is there any particular reason you want to use ClassMatchers in Scala, instead of just using Kompics Scala and taking advantage of the full pattern matching support there?

**Comment by Bathtor** [comment]
Ok, I found a few minutes to look over this quickly, and I think the reason for the issue is that I was lazy with carrying through the generics for the MatchedHandlers in Java, but the Java compiler is not particularly strict about generics, so it just happens to work there, while the Scala compiler actually deals with this properly and complains. The runtime error is just an artefact of actually picking the technically wrong generics (i.e. an existential type) that just happen to compile.

I'll keep this issue around as a bug for now, and will try to fix it eventually, but it's not super high on my priority list, as it works in Java and in Scala you anyway have better facilities with proper pattern matching available.

Thanks for pointing it out, though. :)

**Comment by mboogerd** [comment]
You're welcome. It's not that I desperately need the feature, like you said, there are Scala-specific facilities to do this. Just came across this while following the tutorials, so figured I'd log it. Good luck!
